/**
 * VMEC-01 Master Clinical Catalog
 * 17 Primary Medical Specialties & Subspecialties, Doctor Directory & BYT Guidelines.
 */

export interface MasterDoctor {
  id: string;
  fullName: string;
  title: string; // e.g. "BS.CKII", "PGS.TS", "TS.BS", "ThS.BS"
  avatar: string;
  specialtyCode: string;
  specialtyName: string;
  subspecialties: string[];
  room: string;
  building: string;
  facilityName: string;
  facilityAddress: string;
  experienceYears: number;
  bio: string;
  consultationFee: number;
  availableDays: string[]; // e.g. ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"]
}

export interface MasterCitation {
  sourceId: string;
  documentId: string;
  label: string;
  url: string;
  sectionTitle: string;
  confidence: number;
  snippet: string;
}

export interface MasterSpecialty {
  code: string;
  name: string;
  vietnameseName: string;
  englishName: string;
  description: string;
  subspecialties: string[];
  primaryDoctorId: string;
  doctors: MasterDoctor[];
  room: string;
  building: string;
  facilityName: string;
  facilityAddress: string;
  keywords: string[];
  reasoningTemplate: string;
  citations: MasterCitation[];
}

export const MASTER_DOCTORS: MasterDoctor[] = [
  {
    id: "doc_tim_mach_01",
    fullName: "BS.CKII Trần Minh Đức",
    title: "Bác sĩ Chuyên khoa II - Trưởng khoa",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "TIM_MACH",
    specialtyName: "Khoa Tim Mạch",
    subspecialties: ["Tim mạch can thiệp", "Rối loạn nhịp tim", "Suy tim & Bệnh mạch vành"],
    room: "Phòng 302",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 24,
    bio: "Hơn 24 năm kinh nghiệm trong can thiệp tim mạch và điều trị các bệnh lý rối loạn nhịp tim phức tạp.",
    consultationFee: 450000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_tieu_hoa_01",
    fullName: "TS.BS Nguyễn Thị Mai Lan",
    title: "Tiến sĩ, Bác sĩ - Phó Trưởng khoa",
    avatar: "https://images.unsplash.com/photo-1594824813598-f9b88d3e2307?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "TIEU_HOA",
    specialtyName: "Khoa Tiêu Hóa - Gan Mật",
    subspecialties: ["Nội soi tiêu hóa can thiệp", "Bệnh lý dạ dày - tá tràng", "Gan mật tụy & Viêm gan"],
    room: "Phòng 205",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 18,
    bio: "Chuyên gia nội soi đường tiêu hóa không đau, chẩn đoán sớm ung thư đường tiêu hóa và bệnh lý gan mật.",
    consultationFee: 400000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_ho_hap_01",
    fullName: "BS.CKI Vũ Quốc Tuấn",
    title: "Bác sĩ Chuyên khoa I",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "HO_HAP",
    specialtyName: "Khoa Hô Hấp & Phổi",
    subspecialties: ["Hen phế quản & COPD", "Viêm phế quản - Phổi", "Hội chứng ngưng thở khi ngủ"],
    room: "Phòng 310",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 15,
    bio: "Chuyên sâu về thăm dò chức năng thông khí phổi, điều trị hen phế quản nặng và bệnh phổi tắc nghẽn mạn tính.",
    consultationFee: 350000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6"],
  },
  {
    id: "doc_than_kinh_01",
    fullName: "PGS.TS Hoàng Văn Bách",
    title: "Phó Giáo sư, Tiến sĩ - Cố vấn chuyên môn",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "THAN_KINH",
    specialtyName: "Khoa Thần Kinh & Đột Quỵ",
    subspecialties: ["Dự phòng & Phục hồi Đột quỵ", "Rối loạn Tiền đình & Đau đầu", "Bệnh Parkinson & Sa sút trí tuệ"],
    room: "Phòng 401",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 28,
    bio: "Chuyên gia đầu ngành về Thần kinh học, có nhiều công trình nghiên cứu về đột quỵ não và rối loạn tiền đình trung ương.",
    consultationFee: 500000,
    availableDays: ["Thứ 2", "Thứ 4", "Thứ 6"],
  },
  {
    id: "doc_co_xuong_khop_01",
    fullName: "BS.CKII Phạm Hoàng Quân",
    title: "Bác sĩ Chuyên khoa II",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "CO_XUONG_KHOP",
    specialtyName: "Khoa Cơ Xương Khớp & Cột Sống",
    subspecialties: ["Thoái hóa khớp & Cột sống", "Viêm khớp dạng thấp & Gout", "Y học thể thao & Tiêm khớp"],
    room: "Phòng 212",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 20,
    bio: "Chuyên điều trị thoái hóa khớp gối, thoát vị đĩa đệm cột sống và các kỹ thuật tiêm huyết tương giàu tiểu cầu (PRP).",
    consultationFee: 400000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_da_lieu_01",
    fullName: "ThS.BS Nguyễn Thùy Linh",
    title: "Thạc sĩ, Bác sĩ Da liễu",
    avatar: "https://images.unsplash.com/photo-1594824813600-843b0069ba30?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "DA_LIEU",
    specialtyName: "Khoa Da Liễu & Dị Ứng",
    subspecialties: ["Dị ứng tiếp xúc & Mày đay", "Viêm da cơ địa & Chàm", "Da liễu thẩm mỹ & Laser"],
    room: "Phòng 104",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 12,
    bio: "Chuyên gia về chẩn đoán dị ứng da, điều trị các bệnh da tự miễn và ứng dụng công nghệ laser trong da liễu.",
    consultationFee: 350000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_tai_mui_hong_01",
    fullName: "BS.CKII Lê Văn Hùng",
    title: "Bác sĩ Chuyên khoa II",
    avatar: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "TAI_MUI_HONG",
    specialtyName: "Khoa Tai Mũi Họng",
    subspecialties: ["Nội soi Tai Mũi Họng", "Viêm xoang & Dị ứng mũi", "Thính học & Phẫu thuật thanh quản"],
    room: "Phòng 208",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 22,
    bio: "Kinh nghiệm dày dặn trong phẫu thuật nội soi mũi xoang, vi phẫu thanh quản và điều trị viêm amidan mạn tính.",
    consultationFee: 400000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6"],
  },
  {
    id: "doc_mat_01",
    fullName: "TS.BS Phạm Phương Thảo",
    title: "Tiến sĩ, Bác sĩ Nhãn khoa",
    avatar: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "MAT",
    specialtyName: "Khoa Mắt (Nhãn Khoa)",
    subspecialties: ["Khúc xạ & Lasik", "Đục thủy tinh thể (Phaco)", "Bệnh lý đáy mắt & Glaucoma"],
    room: "Phòng 106",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 16,
    bio: "Chuyên gia phẫu thuật Phaco điều trị đục thủy tinh thể và kiểm soát tật khúc xạ tiến triển ở thanh thiếu niên.",
    consultationFee: 400000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_rang_ham_mat_01",
    fullName: "BS.CKI Nguyễn Quốc Bảo",
    title: "Bác sĩ Chuyên khoa I",
    avatar: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "RANG_HAM_MAT",
    specialtyName: "Khoa Răng Hàm Mặt",
    subspecialties: ["Cấy ghép Implant", "Chỉnh nha thẩm mỹ", "Điều trị tủy & Phẫu thuật nhổ răng khôn"],
    room: "Phòng 102",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 14,
    bio: "Bác sĩ phục hình răng sứ thẩm mỹ, cấy ghép implant nha khoa và nắn chỉnh răng công nghệ cao.",
    consultationFee: 350000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_than_tiet_nieu_01",
    fullName: "BS.CKII Đặng Minh Tuấn",
    title: "Bác sĩ Chuyên khoa II",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "THAN_TIET_NIEU",
    specialtyName: "Khoa Thận - Tiết Niệu & Nam Học",
    subspecialties: ["Sỏi đường tiết niệu & Tán sỏi", "Bệnh lý Thận & Suy thận mạn", "Nam học & Rối loạn tiểu tiện"],
    room: "Phòng 305",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 21,
    bio: "Chuyên gia phẫu thuật nội soi tán sỏi thận qua da (PCNL), điều trị phì đại lành tính tuyến tiền liệt và bệnh lý nam khoa.",
    consultationFee: 400000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6"],
  },
  {
    id: "doc_noi_tiet_01",
    fullName: "ThS.BS Đỗ Thị Thu Trang",
    title: "Thạc sĩ, Bác sĩ Nội tiết",
    avatar: "https://images.unsplash.com/photo-1594824813600-843b0069ba30?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "NOI_TIET",
    specialtyName: "Khoa Nội Tiết & Đái Tháo Đường",
    subspecialties: ["Đái tháo đường & Biến chứng", "Bệnh lý Tuyến giáp (Basedow, Suy giáp)", "Rối loạn chuyển hóa & Béo phì"],
    room: "Phòng 201",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 13,
    bio: "Chuyên sâu về quản lý đái tháo đường cá thể hóa, siêu âm chẩn đoán nhân tuyến giáp và chọc hút tế bào kim nhỏ (FNA).",
    consultationFee: 350000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_nhi_khoa_01",
    fullName: "ThS.BS Lê Thu Trang",
    title: "Thạc sĩ, Bác sĩ Nhi khoa - Trưởng khoa",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "NHI_KHOA",
    specialtyName: "Khoa Nhi & Sơ Sinh",
    subspecialties: ["Nhi tổng quát & Cấp cứu nhi", "Hô hấp & Dị ứng trẻ em", "Dinh dưỡng & Tiêm chủng"],
    room: "Phòng 108",
    building: "Tòa Nhi đồng",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 17,
    bio: "Tận tâm trong khám và điều trị các bệnh lý hô hấp, tiêu hóa, sốt virus và tư vấn dinh dưỡng toàn diện cho trẻ nhỏ.",
    consultationFee: 350000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_san_phu_khoa_01",
    fullName: "BS.CKII Bùi Thị Thanh Hà",
    title: "Bác sĩ Chuyên khoa II - Trưởng khoa",
    avatar: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "SAN_PHU_KHOA",
    specialtyName: "Khoa Sản Phụ Khoa",
    subspecialties: ["Quản lý thai nghén & Tiền sản", "Khám & Điều trị Phụ khoa", "Sàng lọc Ung thư cổ tử cung & U xơ"],
    room: "Phòng 301",
    building: "Tòa Sản Phụ",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 23,
    bio: "Chuyên gia siêu âm thai 5D hình thái học, quản lý thai kỳ nguy cơ cao và phẫu thuật nội soi phụ khoa.",
    consultationFee: 450000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_lao_khoa_01",
    fullName: "PGS.TS Trần Đình Long",
    title: "Phó Giáo sư, Tiến sĩ - Chuyên gia Lão khoa",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "LAO_KHOA",
    specialtyName: "Khoa Lão Khoa & Đa Bệnh Lý",
    subspecialties: ["Đa bệnh lý mạn tính người già", "Hội chứng sa sút trí tuệ (Alzheimer)", "Nguy cơ té ngã & Suy kiệt"],
    room: "Phòng 105",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 30,
    bio: "Chuyên gia hàng đầu về tối ưu hóa đơn thuốc cho người cao tuổi, giảm thiểu tương tác thuốc và phục hồi chức năng lão khoa.",
    consultationFee: 500000,
    availableDays: ["Thứ 3", "Thứ 5", "Thứ 7"],
  },
  {
    id: "doc_tam_than_01",
    fullName: "ThS.BS Vương Thị Hạnh",
    title: "Thạc sĩ, Bác sĩ Tâm lý Lâm sàng",
    avatar: "https://images.unsplash.com/photo-1594824813598-f9b88d3e2307?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "TAM_THAN_TAM_LY",
    specialtyName: "Khoa Sức Khỏe Tâm Thần & Tâm Lý",
    subspecialties: ["Rối loạn Lo âu & Trầm cảm", "Mất ngủ mạn tính & Stress", "Trị liệu Tâm lý & Sang chấn"],
    room: "Phòng 405",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 14,
    bio: "Chuyên sâu về tham vấn tâm lý, can thiệp rối loạn lo âu lan tỏa, rối loạn hoảng sợ và điều trị mất ngủ không dùng thuốc.",
    consultationFee: 400000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6"],
  },
  {
    id: "doc_truyen_nhiem_01",
    fullName: "BS.CKI Ngô Đức Trọng",
    title: "Bác sĩ Chuyên khoa I",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "TRUYEN_NHIEM",
    specialtyName: "Khoa Bệnh Truyền Nhiễm & Nhiệt Đới",
    subspecialties: ["Sốt xuất huyết Dengue", "Cúm, Sốt phát ban & Virus", "Bệnh lý Ký sinh trùng & Dịch tễ"],
    room: "Phòng 103",
    building: "Khu Khám Truyền Nhiễm",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 16,
    bio: "Kinh nghiệm điều trị các bệnh dịch theo mùa, sốt xuất huyết có dấu hiệu cảnh báo và kiểm soát lây nhiễm bệnh viện.",
    consultationFee: 350000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
  {
    id: "doc_noi_tong_quat_01",
    fullName: "BS.CKI Đỗ Quang Huy",
    title: "Bác sĩ Chuyên khoa I - Trưởng phòng khám",
    avatar: "https://images.unsplash.com/photo-1550831107-1553da8c8464?w=160&auto=format&fit=crop&q=80",
    specialtyCode: "NOI_TONG_QUAT",
    specialtyName: "Khoa Nội Tổng Quát & Tầm Soát",
    subspecialties: ["Khám sức khỏe tổng quát định kỳ", "Tầm soát sớm ung thư", "Tư vấn lối sống & Đánh giá nguy cơ"],
    room: "Phòng 101",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    experienceYears: 18,
    bio: "Chuyên trách các gói tầm soát sức khỏe chuyên sâu, phân tích chỉ số sinh hóa máu và lập kế hoạch chăm sóc sức khỏe dự phòng.",
    consultationFee: 300000,
    availableDays: ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
  },
];

export const MASTER_SPECIALTIES: MasterSpecialty[] = [
  {
    code: "TIM_MACH",
    name: "Khoa Tim Mạch",
    vietnameseName: "Khoa Tim Mạch",
    englishName: "Cardiology & Vascular Center",
    description: "Khám, chẩn đoán và điều trị bệnh lý tim mạch, huyết áp, rối loạn nhịp và mạch vành.",
    subspecialties: ["Tim mạch can thiệp", "Rối loạn nhịp tim", "Suy tim & Bệnh mạch vành"],
    primaryDoctorId: "doc_tim_mach_01",
    doctors: [MASTER_DOCTORS[0]],
    room: "Phòng 302",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["tim", "ngực", "tức ngực", "đau ngực", "hồi hộp", "đánh trống ngực", "huyết áp", "mạch", "mạch nhanh", "khoang ngực"],
    reasoningTemplate: "Triệu chứng đau tức ngực và hồi hộp có nguy cơ liên quan đến hệ tuần hoàn và cơ tim, cần được đo ECG và siêu âm tim chuyên sâu.",
    citations: [
      {
        sourceId: "BYT_CIRCULAR_2026",
        documentId: "QĐ-3983/QĐ-BYT",
        label: "Hướng dẫn chẩn đoán và xử trí Hội chứng mạch vành cấp (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Mục 2.1: Phân tầng nguy cơ đau ngực & Chỉ định đo điện tâm đồ 12 chuyển đạo",
        confidence: 96,
        snippet: "Bệnh nhân có triệu chứng đau ngực khi gắng sức hoặc kèm hồi hộp cần được tiếp cận ban đầu theo quy chuẩn đo ECG trong vòng 10 phút đầu.",
      },
    ],
  },
  {
    code: "TIEU_HOA",
    name: "Khoa Tiêu Hóa - Gan Mật",
    vietnameseName: "Khoa Tiêu Hóa - Gan Mật",
    englishName: "Gastroenterology & Hepatology",
    description: "Chẩn đoán và điều trị bệnh lý đường tiêu hóa, gan mật tụy và nội soi tiêu hóa can thiệp.",
    subspecialties: ["Nội soi tiêu hóa can thiệp", "Bệnh lý dạ dày - tá tràng", "Gan mật tụy & Viêm gan"],
    primaryDoctorId: "doc_tieu_hoa_01",
    doctors: [MASTER_DOCTORS[1]],
    room: "Phòng 205",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["dạ dày", "thượng vị", "ợ chua", "ợ nóng", "đau bụng", "tiêu hóa", "buồn nôn", "trào ngược", "gan", "mật", "đại tràng"],
    reasoningTemplate: "Các triệu chứng đau rát vùng thượng vị và ợ chua định hướng bệnh lý viêm loét dạ dày - tá tràng hoặc trào ngược dạ dày thực quản (GERD).",
    citations: [
      {
        sourceId: "VNAGE_GUIDELINE",
        documentId: "VNAGE-GERD-2026",
        label: "Hướng dẫn chẩn đoán và điều trị Bệnh trào ngược dạ dày thực quản (Hội Tiêu Hóa VN)",
        url: "http://tieuhoa.vn",
        sectionTitle: "Phần 3: Phác đồ thăm khám lâm sàng & Điều trị ức chế tiết acid PPI",
        confidence: 95,
        snippet: "Triệu chứng nóng rát sau xương ức và ợ chua là tiêu chuẩn lâm sàng điển hình cho chẩn đoán ban đầu của GERD.",
      },
    ],
  },
  {
    code: "HO_HAP",
    name: "Khoa Hô Hấp & Phổi",
    vietnameseName: "Khoa Hô Hấp & Phổi",
    englishName: "Pulmonology & Respiratory Medicine",
    description: "Khám và điều trị các bệnh lý phế quản, phổi, hen suyễn và rối loạn thông khí.",
    subspecialties: ["Hen phế quản & COPD", "Viêm phế quản - Phổi", "Hội chứng ngưng thở khi ngủ"],
    primaryDoctorId: "doc_ho_hap_01",
    doctors: [MASTER_DOCTORS[2]],
    room: "Phòng 310",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["phổi", "hô hấp", "ho", "ho có đờm", "khó thở", "viêm họng", "viêm phế quản", "khò khè", "đờm"],
    reasoningTemplate: "Triệu chứng ho dai dẳng kèm khó thở cần được chỉ định chụp X-quang ngực thẳng và đo chức năng thông khí phổi.",
    citations: [
      {
        sourceId: "BYT_RESP_2026",
        documentId: "QĐ-4015/QĐ-BYT",
        label: "Hướng dẫn chẩn đoán và điều trị Bệnh phổi tắc nghẽn mạn tính & Viêm phế quản (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Phần 2: Quy trình đo chức năng hô hấp và xét nghiệm đờm vi sinh",
        confidence: 95,
        snippet: "Đánh giá mức độ tắc nghẽn đường thở và loại trừ bội nhiễm vi khuẩn bằng phim X-quang lồng ngực.",
      },
    ],
  },
  {
    code: "THAN_KINH",
    name: "Khoa Thần Kinh & Đột Quỵ",
    vietnameseName: "Khoa Thần Kinh & Đột Quỵ",
    englishName: "Neurology & Stroke Center",
    description: "Khám và điều trị đau đầu, chóng mặt, tiền đình, đột quỵ não và bệnh thần kinh cơ.",
    subspecialties: ["Dự phòng & Phục hồi Đột quỵ", "Rối loạn Tiền đình & Đau đầu", "Bệnh Parkinson & Sa sút trí tuệ"],
    primaryDoctorId: "doc_than_kinh_01",
    doctors: [MASTER_DOCTORS[3]],
    room: "Phòng 401",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["đầu", "đau đầu", "chóng mặt", "hoa mắt", "mất ngủ", "tê bì", "rối loạn tiền đình", "ngất", "choáng", "buốt đầu"],
    reasoningTemplate: "Triệu chứng hoa mắt chóng mặt khi thay đổi tư thế hướng tới hội chứng rối loạn tiền đình hoặc thiểu năng tuần hoàn não.",
    citations: [
      {
        sourceId: "VNNA_GUIDELINE",
        documentId: "VNNA-VERTIGO-2026",
        label: "Khuyến cáo chẩn đoán và xử trí Hội chứng Tiền đình (Hội Thần Kinh VN)",
        url: "http://thankinhhoc.vn",
        sectionTitle: "Mục 1.3: Nghiệm pháp định vị tiền đình và phân biệt chóng mặt ngoại biên",
        confidence: 94,
        snippet: "Khám chuyên khoa Thần kinh và thực hiện nghiệm pháp định vị tiền đình giúp xác định chính xác nguyên nhân chóng mặt.",
      },
    ],
  },
  {
    code: "CO_XUONG_KHOP",
    name: "Khoa Cơ Xương Khớp & Cột Sống",
    vietnameseName: "Khoa Cơ Xương Khớp & Cột Sống",
    englishName: "Rheumatology & Orthopedics",
    description: "Điều trị thoái hóa khớp, thoát vị đĩa đệm cột sống, viêm khớp tự miễn và gout.",
    subspecialties: ["Thoái hóa khớp & Cột sống", "Viêm khớp dạng thấp & Gout", "Y học thể thao & Tiêm khớp"],
    primaryDoctorId: "doc_co_xuong_khop_01",
    doctors: [MASTER_DOCTORS[4]],
    room: "Phòng 212",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["khớp", "xương", "đầu gối", "lưng", "cột sống", "đau lưng", "thoái hóa", "vai gáy", "gout", "bẻ khớp", "đau khớp"],
    reasoningTemplate: "Đau mỏi và cứng khớp định hướng thoái hóa khớp hoặc viêm khớp, cần thăm khám lâm sàng và chụp MRI khớp liên quan.",
    citations: [
      {
        sourceId: "BYT_RHEUM_2026",
        documentId: "QĐ-361/QĐ-BYT",
        label: "Hướng dẫn chẩn đoán và điều trị các bệnh Cơ Xương Khớp (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Chương 1: Tiêu chuẩn chẩn đoán Thoái hóa khớp gối và Cột sống thắt lưng",
        confidence: 96,
        snippet: "Chỉ định chụp X-quang khớp tư thế chịu lực và xét nghiệm acid uric máu để phân biệt thoái hóa với viêm khớp do gout.",
      },
    ],
  },
  {
    code: "DA_LIEU",
    name: "Khoa Da Liễu & Dị Ứng",
    vietnameseName: "Khoa Da Liễu & Dị Ứng",
    englishName: "Dermatology & Clinical Allergology",
    description: "Chẩn đoán bệnh da dị ứng, viêm da cơ địa, mụn trứng cá, vảy nến và da liễu thẩm mỹ.",
    subspecialties: ["Dị ứng tiếp xúc & Mày đay", "Viêm da cơ địa & Chàm", "Da liễu thẩm mỹ & Laser"],
    primaryDoctorId: "doc_da_lieu_01",
    doctors: [MASTER_DOCTORS[5]],
    room: "Phòng 104",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["da", "mẩn ngứa", "dị ứng da", "mụn", "chàm", "mề đay", "vảy nến", "nấm da", "ngứa ngáy", "nốt đỏ"],
    reasoningTemplate: "Nổi mẩn ngứa và tổn thương da cần được soi tươi tìm nấm, xét nghiệm dị nguyên và dùng phác đồ kháng histamine thích hợp.",
    citations: [
      {
        sourceId: "NVD_DERMA_2026",
        documentId: "NVD-PROTOCOL-2026",
        label: "Phác đồ điều trị Da liễu Lâm sàng (Bệnh viện Da liễu Trung ương)",
        url: "https://dalieu.vn",
        sectionTitle: "Mục 4: Tiếp cận bệnh nhân Mày đay cấp và Viêm da tiếp xúc dị ứng",
        confidence: 95,
        snippet: "Loại bỏ tiếp xúc với yếu tố nghi ngờ dị nguyên và dùng thuốc kháng histamine thế hệ 2 đường uống.",
      },
    ],
  },
  {
    code: "TAI_MUI_HONG",
    name: "Khoa Tai Mũi Họng",
    vietnameseName: "Khoa Tai Mũi Họng",
    englishName: "Otorhinolaryngology (ENT)",
    description: "Khám và điều trị viêm tai giữa, viêm xoang, viêm họng thanh quản và thính học.",
    subspecialties: ["Nội soi Tai Mũi Họng", "Viêm xoang & Dị ứng mũi", "Thính học & Phẫu thuật thanh quản"],
    primaryDoctorId: "doc_tai_mui_hong_01",
    doctors: [MASTER_DOCTORS[6]],
    room: "Phòng 208",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["tai", "mũi", "họng", "ù tai", "chảy mũi", "ngạt mũi", "khàn tiếng", "viêm amidan", "viêm xoang", "đau họng"],
    reasoningTemplate: "Các triệu chứng ngạt mũi, chảy dịch hoặc khàn tiếng cần nội soi ống mềm Tai Mũi Họng để đánh giá niêm mạc và thanh quản.",
    citations: [
      {
        sourceId: "BYT_ENT_2026",
        documentId: "QĐ-1892/QĐ-BYT",
        label: "Hướng dẫn Quy trình Kỹ thuật Chuyên ngành Tai Mũi Họng (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Quy trình nội soi tai mũi họng dải tần hẹp (NBI)",
        confidence: 95,
        snippet: "Nội soi NBI giúp phát hiện sớm các tổn thương tiền ung thư vòm họng và niêm mạc xoang.",
      },
    ],
  },
  {
    code: "MAT",
    name: "Khoa Mắt (Nhãn Khoa)",
    vietnameseName: "Khoa Mắt (Nhãn Khoa)",
    englishName: "Ophthalmology Center",
    description: "Khám tật khúc xạ, đo thị lực, phẫu thuật Phaco đục thủy tinh thể và bệnh lý đáy mắt.",
    subspecialties: ["Khúc xạ & Lasik", "Đục thủy tinh thể (Phaco)", "Bệnh lý đáy mắt & Glaucoma"],
    primaryDoctorId: "doc_mat_01",
    doctors: [MASTER_DOCTORS[7]],
    room: "Phòng 106",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["mắt", "nhìn mờ", "cận thị", "đau mắt", "đỏ mắt", "chảy nước mắt", "thị lực", "mộng thịt", "đục thủy tinh thể"],
    reasoningTemplate: "Tình trạng nhìn mờ hoặc đau nhức hốc mắt cần được đo khúc xạ máy, đo nhãn áp và soi đáy mắt chuyên sâu.",
    citations: [
      {
        sourceId: "BYT_EYE_2026",
        documentId: "QĐ-2991/QĐ-BYT",
        label: "Quy trình Khám và Điều trị các Bệnh Nhãn khoa (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Quy chuẩn đo nhãn áp kế Maclakov và soi góc tiền phòng",
        confidence: 94,
        snippet: "Bệnh nhân có cảm giác căng tức mắt cần đo nhãn áp loại trừ bệnh tăng nhãn áp (Glaucoma) cấp tính.",
      },
    ],
  },
  {
    code: "RANG_HAM_MAT",
    name: "Khoa Răng Hàm Mặt",
    vietnameseName: "Khoa Răng Hàm Mặt",
    englishName: "Dental & Maxillofacial Center",
    description: "Khám và điều trị sâu răng, tủy răng, cấy ghép implant, chỉnh nha và nhổ răng khôn.",
    subspecialties: ["Cấy ghép Implant", "Chỉnh nha thẩm mỹ", "Điều trị tủy & Phẫu thuật nhổ răng khôn"],
    primaryDoctorId: "doc_rang_ham_mat_01",
    doctors: [MASTER_DOCTORS[8]],
    room: "Phòng 102",
    building: "Tòa nhà C",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["răng", "sâu răng", "đau răng", "lợi", "nướu", "chảy máu chân răng", "răng khôn", "niềng răng", "hàm", "buốt răng"],
    reasoningTemplate: "Cơn đau buốt răng lan lên thái dương cần chụp X-quang Panorama toàn hàm và kiểm tra buồng tủy răng.",
    citations: [
      {
        sourceId: "BYT_DENTAL_2026",
        documentId: "QĐ-3104/QĐ-BYT",
        label: "Hướng dẫn Quy trình Kỹ thuật Khám chữa bệnh Răng Hàm Mặt (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Phác đồ điều trị Viêm tủy răng và Viêm quanh cuống cấp",
        confidence: 96,
        snippet: "Chụp phim X-quang chóp răng là bắt buộc để đánh giá tổn thương cuống răng và chiều dài ống tủy.",
      },
    ],
  },
  {
    code: "THAN_TIET_NIEU",
    name: "Khoa Thận - Tiết Niệu & Nam Học",
    vietnameseName: "Khoa Thận - Tiết Niệu & Nam Học",
    englishName: "Nephrology & Urology Center",
    description: "Khám sỏi thận, viêm đường tiết niệu, phì đại tuyến tiền liệt và bệnh lý nam khoa.",
    subspecialties: ["Sỏi đường tiết niệu & Tán sỏi", "Bệnh lý Thận & Suy thận mạn", "Nam học & Rối loạn tiểu tiện"],
    primaryDoctorId: "doc_than_tiet_nieu_01",
    doctors: [MASTER_DOCTORS[9]],
    room: "Phòng 305",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["thận", "tiết niệu", "tiểu buốt", "tiểu rắt", "tiểu ra máu", "sỏi thận", "đau hông lưng", "nam học", "tuyến tiền liệt"],
    reasoningTemplate: "Biểu hiện tiểu buốt, tiểu rắt hoặc đau quặn hông lưng cần siêu âm hệ tiết niệu và xét nghiệm tổng phân tích nước tiểu.",
    citations: [
      {
        sourceId: "BYT_URO_2026",
        documentId: "QĐ-3890/QĐ-BYT",
        label: "Hướng dẫn Chẩn đoán và Điều trị Bệnh học Tiết Niệu (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Chẩn đoán và xử trí cơn đau quặn thận do sỏi niệu quản",
        confidence: 95,
        snippet: "Siêu âm Doppler và chụp cắt lớp vi tính hệ tiết niệu (CT Scanner) không cản quang giúp định vị chính xác vị trí sỏi.",
      },
    ],
  },
  {
    code: "NOI_TIET",
    name: "Khoa Nội Tiết & Đái Tháo Đường",
    vietnameseName: "Khoa Nội Tiết & Đái Tháo Đường",
    englishName: "Endocrinology & Diabetes",
    description: "Quản lý đái tháo đường, rối loạn chuyển hóa lipid, bệnh lý tuyến giáp và tuyến thượng thận.",
    subspecialties: ["Đái tháo đường & Biến chứng", "Bệnh lý Tuyến giáp (Basedow, Suy giáp)", "Rối loạn chuyển hóa & Béo phì"],
    primaryDoctorId: "doc_noi_tiet_01",
    doctors: [MASTER_DOCTORS[10]],
    room: "Phòng 201",
    building: "Tòa nhà B",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["đường huyết", "tiểu đường", "đái tháo đường", "tuyến giáp", "bướu cổ", "basedow", "suy giáp", "u giáp", "uống nhiều tiểu nhiều"],
    reasoningTemplate: "Bệnh nhân có triệu chứng ăn nhiều, uống nhiều, sụt cân hoặc bướu cổ cần làm xét nghiệm HbA1c, định lượng hormon TSH, FT4.",
    citations: [
      {
        sourceId: "BYT_ENDO_2026",
        documentId: "QĐ-5481/QĐ-BYT",
        label: "Hướng dẫn chẩn đoán và điều trị Đái tháo đường típ 2 (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Tiêu chuẩn chẩn đoán ĐTĐ dựa trên đường huyết tương lúc đói và HbA1c",
        confidence: 97,
        snippet: "Đo HbA1c chuẩn hóa theo phương pháp NGSP giúp đánh giá kiểm soát đường huyết trung bình trong 3 tháng.",
      },
    ],
  },
  {
    code: "NHI_KHOA",
    name: "Khoa Nhi & Sơ Sinh",
    vietnameseName: "Khoa Nhi & Sơ Sinh",
    englishName: "Pediatrics & Neonatology",
    description: "Chăm sóc toàn diện cho trẻ sơ sinh và trẻ nhỏ: bệnh lý hô hấp, tiêu hóa, sốt và dinh dưỡng.",
    subspecialties: ["Nhi tổng quát & Cấp cứu nhi", "Hô hấp & Dị ứng trẻ em", "Dinh dưỡng & Tiêm chủng"],
    primaryDoctorId: "doc_nhi_khoa_01",
    doctors: [MASTER_DOCTORS[11]],
    room: "Phòng 108",
    building: "Tòa Nhi đồng",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["con", "bé", "cháu", "trẻ", "nhi", "sốt ở trẻ", "ho sổ mũi ở bé", "biếng ăn", "tiêu chảy ở trẻ", "quấy khóc"],
    reasoningTemplate: "Bệnh nhi có dấu hiệu sốt và viêm đường hô hấp trên, cần được bác sĩ Nhi khoa thăm khám trực tiếp và theo dõi sát chỉ số sinh tồn.",
    citations: [
      {
        sourceId: "BYT_PED_2026",
        documentId: "QĐ-3312/QĐ-BYT",
        label: "Hướng dẫn chẩn đoán và điều trị một số bệnh thường gặp ở Trẻ em (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Chương 2: Đánh giá và xử trí trẻ sốt cấp tính & Viêm đường hô hấp trên",
        confidence: 97,
        snippet: "Trẻ sốt kèm ho sổ mũi cần theo dõi sát nhịp thở, dấu hiệu rút lõm lồng ngực và tình trạng tỉnh táo/bú mẹ.",
      },
    ],
  },
  {
    code: "SAN_PHU_KHOA",
    name: "Khoa Sản Phụ Khoa",
    vietnameseName: "Khoa Sản Phụ Khoa",
    englishName: "Obstetrics & Gynecology (OB/GYN)",
    description: "Khám thai định kỳ, sàng lọc dị tật thai, khám chữa bệnh phụ khoa và tư vấn tiền sản.",
    subspecialties: ["Quản lý thai nghén & Tiền sản", "Khám & Điều trị Phụ khoa", "Sàng lọc Ung thư cổ tử cung & U xơ"],
    primaryDoctorId: "doc_san_phu_khoa_01",
    doctors: [MASTER_DOCTORS[12]],
    room: "Phòng 301",
    building: "Tòa Sản Phụ",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["thai", "có bầu", "mang thai", "phụ khoa", "khí hư", "kinh nguyệt", "chậm kinh", "đau bụng dưới ở nữ", "siêu âm thai"],
    reasoningTemplate: "Các vấn đề về thai nghén hoặc rối loạn chu kỳ kinh nguyệt cần được bác sĩ Sản Phụ khoa siêu âm đầu dò/ổ bụng và khám phụ khoa.",
    citations: [
      {
        sourceId: "BYT_OBGYN_2026",
        documentId: "QĐ-4325/QĐ-BYT",
        label: "Hướng dẫn Quốc gia về các Dịch vụ Chăm sóc Sức khỏe Sinh sản (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Quy trình quản lý thai kỳ chuẩn 8 mốc khám thai thiết yếu",
        confidence: 96,
        snippet: "Thực hiện siêu âm hình thái học ở tuần 11-13 tuần 6 ngày để đo độ mờ da gáy và xét nghiệm sàng lọc tiền sản.",
      },
    ],
  },
  {
    code: "LAO_KHOA",
    name: "Khoa Lão Khoa & Đa Bệnh Lý",
    vietnameseName: "Khoa Lão Khoa & Đa Bệnh Lý",
    englishName: "Geriatrics & Chronic Care",
    description: "Khám và điều trị tổng thể cho người cao tuổi mắc nhiều bệnh mạn tính kết hợp.",
    subspecialties: ["Đa bệnh lý mạn tính người già", "Hội chứng sa sút trí tuệ (Alzheimer)", "Nguy cơ té ngã & Suy kiệt"],
    primaryDoctorId: "doc_lao_khoa_01",
    doctors: [MASTER_DOCTORS[13]],
    room: "Phòng 105",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["người già", "ông bà", "cao tuổi", "lú lẫn", "hay quên ở người già", "run tay", "suy yếu", "đa bệnh mạn tính"],
    reasoningTemplate: "Người cao tuổi có biểu hiện sa sút trí nhớ hoặc đa bệnh mạn tính cần được bác sĩ Lão khoa đánh giá toàn diện và rà soát tương tác thuốc.",
    citations: [
      {
        sourceId: "BYT_GERIA_2026",
        documentId: "QĐ-2710/QĐ-BYT",
        label: "Hướng dẫn Chăm sóc Sức khỏe Người cao tuổi Toàn diện (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Đánh giá toàn diện Lão khoa (CGA) và sàng lọc hội chứng lão hóa",
        confidence: 95,
        snippet: "Đánh giá khả năng hoạt động hàng ngày (ADL/IADL) và giảm thiểu các đơn thuốc không phù hợp theo tiêu chuẩn Beers.",
      },
    ],
  },
  {
    code: "TAM_THAN_TAM_LY",
    name: "Khoa Sức Khỏe Tâm Thần & Tâm Lý",
    vietnameseName: "Khoa Sức Khỏe Tâm Thần & Tâm Lý",
    englishName: "Psychiatry & Clinical Psychology",
    description: "Tham vấn và điều trị rối loạn lo âu, trầm cảm, stress công việc, mất ngủ và khủng hoảng tâm lý.",
    subspecialties: ["Rối loạn Lo âu & Trầm cảm", "Mất ngủ mạn tính & Stress", "Trị liệu Tâm lý & Sang chấn"],
    primaryDoctorId: "doc_tam_than_01",
    doctors: [MASTER_DOCTORS[14]],
    room: "Phòng 405",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["lo âu", "trầm cảm", "stress", "căng thẳng", "mất ngủ kéo dài", "hoảng loạn", "sợ hãi", "buồn bã", "tâm lý bất an"],
    reasoningTemplate: "Biểu hiện căng thẳng, mất ngủ kéo dài và lo âu bất an cần được lượng giá tâm lý bằng thang điểm chuẩn (GAD-7, PHQ-9) và tư vấn chuyên sâu.",
    citations: [
      {
        sourceId: "BYT_PSYCH_2026",
        documentId: "QĐ-4992/QĐ-BYT",
        label: "Hướng dẫn Chẩn đoán và Điều trị Rối loạn Lo âu và Trầm cảm (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Phác đồ lượng giá thang đo tâm lý PHQ-9 và can thiệp trị liệu nhận thức hành vi (CBT)",
        confidence: 94,
        snippet: "Kết hợp đánh giá tâm lý chuẩn mực với trị liệu tâm lý cá nhân và điều chỉnh nhịp sinh học giấc ngủ.",
      },
    ],
  },
  {
    code: "TRUYEN_NHIEM",
    name: "Khoa Bệnh Truyền Nhiễm & Nhiệt Đới",
    vietnameseName: "Khoa Bệnh Truyền Nhiễm & Nhiệt Đới",
    englishName: "Infectious & Tropical Diseases",
    description: "Chẩn đoán và điều trị sốt xuất huyết Dengue, cúm, sốt phát ban, viêm gan virus và nhiễm ký sinh trùng.",
    subspecialties: ["Sốt xuất huyết Dengue", "Cúm, Sốt phát ban & Virus", "Bệnh lý Ký sinh trùng & Dịch tễ"],
    primaryDoctorId: "doc_truyen_nhiem_01",
    doctors: [MASTER_DOCTORS[15]],
    room: "Phòng 103",
    building: "Khu Khám Truyền Nhiễm",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["sốt cao", "sốt xuất huyết", "phát ban", "nhiễm virus", "cúm", "dịch tễ", "sốt rét", "nhiễm trùng", "sốt liên tục"],
    reasoningTemplate: "Sốt cao liên tục kèm đau mỏi người và dấu hiệu phát ban cần xét nghiệm công thức máu, test nhanh NS1 Dengue để loại trừ sốt xuất huyết.",
    citations: [
      {
        sourceId: "BYT_INFECT_2026",
        documentId: "QĐ-2760/QĐ-BYT",
        label: "Hướng dẫn chẩn đoán và điều trị Sốt xuất huyết Dengue (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Nhận diện dấu hiệu cảnh báo sốt xuất huyết và theo dõi tiểu cầu máu",
        confidence: 96,
        snippet: "Bệnh nhân sốt ngày 1-3 cần làm test kháng nguyên Dengue NS1 và tổng phân tích tế bào máu ngoại vi mỗi 24 giờ.",
      },
    ],
  },
  {
    code: "NOI_TONG_QUAT",
    name: "Khoa Nội Tổng Quát & Tầm Soát",
    vietnameseName: "Khoa Nội Tổng Quát & Tầm Soát",
    englishName: "Internal Medicine & Health Screening",
    description: "Khám sức khỏe tổng quát định kỳ, tầm soát ung thư sớm, phân tích đa cơ quan và phòng ngừa bệnh tật.",
    subspecialties: ["Khám sức khỏe tổng quát định kỳ", "Tầm soát sớm ung thư", "Tư vấn lối sống & Đánh giá nguy cơ"],
    primaryDoctorId: "doc_noi_tong_quat_01",
    doctors: [MASTER_DOCTORS[16]],
    room: "Phòng 101",
    building: "Tòa nhà A",
    facilityName: "Bệnh viện Đa khoa Quốc tế VMEC",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    keywords: ["tổng quát", "sức khỏe", "khám tổng thể", "mệt mỏi", "sụt cân", "tầm soát", "kiểm tra định kỳ", "khám định kỳ"],
    reasoningTemplate: "Chỉ định khám Nội tổng quát toàn diện kết hợp gói xét nghiệm máu sinh hóa và siêu âm ổ bụng tổng quát.",
    citations: [
      {
        sourceId: "BYT_CIRCULAR_32",
        documentId: "TT-32/2023/TT-BYT",
        label: "Quy chuẩn Khám sức khỏe định kỳ & Danh mục xét nghiệm thiết yếu (Bộ Y Tế)",
        url: "https://kcb.vn",
        sectionTitle: "Điều 14: Danh mục cận lâm sàng bắt buộc trong gói khám sức khỏe tổng quát",
        confidence: 96,
        snippet: "Quy chuẩn bao gồm xét nghiệm chức năng gan, thận, đường huyết, mỡ máu, chụp X-quang tim phổi và siêu âm ổ bụng.",
      },
    ],
  },
];

/**
 * Quick helpers
 */
export function getSpecialtyByCode(code: string): MasterSpecialty | undefined {
  return MASTER_SPECIALTIES.find((s) => s.code.toUpperCase() === code.toUpperCase());
}

export function getDoctorById(id: string): MasterDoctor | undefined {
  return MASTER_DOCTORS.find((d) => d.id === id);
}

export function getDoctorsBySpecialty(code: string): MasterDoctor[] {
  return MASTER_DOCTORS.filter((d) => d.specialtyCode.toUpperCase() === code.toUpperCase());
}
