import type { Appointment } from "@/lib/api/contracts";

export interface DetailedPatientSnapshot {
  fullName: string;
  phoneNumber: string;
  dateOfBirth: string | null;
  gender: "MALE" | "FEMALE" | "OTHER" | "UNKNOWN";
  address: string | null;
  patientSubject: "SELF" | "RELATIVE";
  relationship?: string | null;
  age?: number | string;
  medicalCode: string;
  bloodType?: string;
  allergies?: string[];
  medicalHistory?: string[];
  vitalSigns?: {
    bloodPressure: string;
    heartRate: number;
    temperature: number;
    spO2: number;
    weight: number;
  };
  aiAssessment?: {
    preliminaryDiagnosis: string;
    urgencyLevel: "ROUTINE" | "URGENT" | "EMERGENCY";
    confidenceScore: number;
    reasoning: string;
  };
  receptionistNote?: string;
  clinicalNote?: string;
}

export interface DetailedAppointment extends Appointment {
  patientDetail: DetailedPatientSnapshot;
}

export const MOCK_DOCTOR_APPOINTMENTS: DetailedAppointment[] = [
  {
    id: "app-doc-001",
    appointmentCode: "APT-2026-0801",
    patientId: "pat-101",
    doctorId: "doc-01",
    doctorName: "BS. CKI Trần Văn Nam",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-01",
    specialtyName: "Khoa Tim Mạch",
    room: "Phòng 302 - Tầng 3",
    scheduleId: "sch-001",
    status: "CONFIRMED",
    bookingReason: "Tức ngực trái nhẹ khi leo cầu thang, kèm hồi hộp đánh trống ngực kéo dài 2 ngày.",
    patientNotes: "Bệnh nhân có mang theo kết quả điện tâm đồ khám tại phòng khám tư tuần trước.",
    receptionistNotes: "Đã xác nhận lịch. Đã hướng dẫn bệnh nhân nhịn ăn sáng để làm xét nghiệm máu nếu cần.",
    cancellationReason: null,
    expiresAt: null,
    confirmedAt: "2026-08-05T08:30:00Z",
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-04T14:20:00Z",
    updatedAt: "2026-08-05T08:30:00Z",
    slotStart: "2026-08-06T09:00:00Z",
    slotEnd: "2026-08-06T09:30:00Z",
    patientSnapshot: {
      full_name: "Nguyễn Văn An",
      phone_number: "0912 345 678",
      gender: "MALE",
      age: 48,
    },
    patientDetail: {
      fullName: "Nguyễn Văn An",
      phoneNumber: "0912 345 678",
      dateOfBirth: "1978-05-14",
      gender: "MALE",
      address: "Số 45 Ngõ 102 Khuất Duy Tiến, Thanh Xuân, Hà Nội",
      patientSubject: "SELF",
      age: 48,
      medicalCode: "BN-2026-8891",
      bloodType: "O+",
      allergies: ["Penicillin", "Aspirin"],
      medicalHistory: ["Tăng huyết áp độ 1 (2 năm)", "Rối loạn lipid máu"],
      vitalSigns: {
        bloodPressure: "135/85",
        heartRate: 78,
        temperature: 36.8,
        spO2: 98,
        weight: 68.5,
      },
      aiAssessment: {
        preliminaryDiagnosis: "Theo dõi Thiếu máu cơ tim cục bộ nhẹ / Rối loạn nhịp xoang",
        urgencyLevel: "URGENT",
        confidenceScore: 88,
        reasoning: "Triệu chứng đau tức ngực trái xuất hiện khi gắng sức (leo cầu thang) ở nam giới 48 tuổi có tiền sử tăng huyết áp.",
      },
      receptionistNote: "Bệnh nhân đến đúng giờ, tâm lý ổn định.",
      clinicalNote: "Đã chỉ định ECG 12 chuyển đạo và siêu âm tim dopler.",
    },
  },
  {
    id: "app-doc-002",
    appointmentCode: "APT-2026-0802",
    patientId: "pat-102",
    doctorId: "doc-01",
    doctorName: "BS. CKI Trần Văn Nam",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-01",
    specialtyName: "Khoa Tim Mạch",
    room: "Phòng 302 - Tầng 3",
    scheduleId: "sch-002",
    status: "CONFIRMED",
    bookingReason: "Tái khám định kỳ tăng huyết áp và điều chỉnh đơn thuốc.",
    patientNotes: "Thuốc đang uống sắp hết.",
    receptionistNotes: "Hồ sơ tái khám hợp lệ.",
    cancellationReason: null,
    expiresAt: null,
    confirmedAt: "2026-08-05T09:15:00Z",
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-04T16:10:00Z",
    updatedAt: "2026-08-05T09:15:00Z",
    slotStart: "2026-08-06T10:00:00Z",
    slotEnd: "2026-08-06T10:30:00Z",
    patientSnapshot: {
      full_name: "Lê Thị Ngọc",
      phone_number: "0988 765 432",
      gender: "FEMALE",
      age: 62,
    },
    patientDetail: {
      fullName: "Lê Thị Ngọc",
      phoneNumber: "0988 765 432",
      dateOfBirth: "1964-11-20",
      gender: "FEMALE",
      address: "Số 12 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội",
      patientSubject: "SELF",
      age: 62,
      medicalCode: "BN-2026-4102",
      bloodType: "A+",
      allergies: ["Không có ghi nhận"],
      medicalHistory: ["Tăng huyết áp nguyên phát (5 năm)", "Đái tháo đường tuýp 2 (3 năm)"],
      vitalSigns: {
        bloodPressure: "128/80",
        heartRate: 72,
        temperature: 36.6,
        spO2: 99,
        weight: 56.0,
      },
      aiAssessment: {
        preliminaryDiagnosis: "Tái khám kiểm soát Tăng huyết áp & Đái tháo đường tuýp 2",
        urgencyLevel: "ROUTINE",
        confidenceScore: 95,
        reasoning: "Tái khám định kỳ theo lịch hẹn 3 tháng.",
      },
      receptionistNote: "Bệnh nhân có BHYT đúng tuyến.",
      clinicalNote: "Huyết áp và đường huyết kiểm soát tốt.",
    },
  },
  {
    id: "app-doc-003",
    appointmentCode: "APT-2026-0803",
    patientId: "pat-103",
    doctorId: "doc-01",
    doctorName: "BS. CKI Trần Văn Nam",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-01",
    specialtyName: "Khoa Tim Mạch",
    room: "Phòng 302 - Tầng 3",
    scheduleId: "sch-003",
    status: "CONFIRMED",
    bookingReason: "Chóng mặt khi thay đổi tư thế đột ngột, cảm giác hoa mắt.",
    patientNotes: "Cần kiểm tra huyết áp tư thế.",
    receptionistNotes: "Đã ưu tiên xếp slot đầu buổi chiều.",
    cancellationReason: null,
    expiresAt: null,
    confirmedAt: "2026-08-05T10:00:00Z",
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-05T07:45:00Z",
    updatedAt: "2026-08-05T10:00:00Z",
    slotStart: "2026-08-06T14:00:00Z",
    slotEnd: "2026-08-06T14:30:00Z",
    patientSnapshot: {
      full_name: "Phạm Quốc Minh",
      phone_number: "0903 112 233",
      gender: "MALE",
      age: 35,
    },
    patientDetail: {
      fullName: "Phạm Quốc Minh",
      phoneNumber: "0903 112 233",
      dateOfBirth: "1991-03-08",
      gender: "MALE",
      address: "Tòa S2.01 Vinhomes Smart City, Nam Từ Liêm, Hà Nội",
      patientSubject: "SELF",
      age: 35,
      medicalCode: "BN-2026-7731",
      bloodType: "B+",
      allergies: ["Hải sản"],
      medicalHistory: ["Hạ huyết áp tư thế nhẹ", "Stress công việc"],
      vitalSigns: {
        bloodPressure: "110/70",
        heartRate: 82,
        temperature: 36.7,
        spO2: 99,
        weight: 72.0,
      },
      aiAssessment: {
        preliminaryDiagnosis: "Theo dõi Hạ huyết áp tư thế / Rối loạn tiền đình nhẹ",
        urgencyLevel: "ROUTINE",
        confidenceScore: 84,
        reasoning: "Bệnh nhân trẻ tuổi, triệu chứng hoa mắt chóng mặt khi đứng dậy đột ngột.",
      },
      receptionistNote: "Bệnh nhân khám tự nguyện không dùng BHYT.",
      clinicalNote: "Tư vấn chế độ nghỉ ngơi, uống đủ nước và tập luyện nhẹ nhàng.",
    },
  },
];

export const MOCK_RECEPTION_QUEUE: Appointment[] = [
  {
    id: "app-rec-001",
    appointmentCode: "APT-PENDING-001",
    patientId: "pat-201",
    doctorId: "doc-02",
    doctorName: "TS.BS Nguyễn Thanh Tùng",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-02",
    specialtyName: "Khoa Tiêu Hóa",
    room: "Phòng 205 - Tầng 2",
    scheduleId: "sch-101",
    status: "PENDING_RECEPTIONIST_APPROVAL",
    bookingReason: "Đau rát vùng thượng vị 3 ngày nay, ợ chua nhiều sau khi ăn đồ cay nóng.",
    patientNotes: "Muốn khám buổi sáng sớm.",
    receptionistNotes: null,
    cancellationReason: null,
    expiresAt: "2026-08-06T12:00:00Z",
    confirmedAt: null,
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-05T11:20:00Z",
    updatedAt: "2026-08-05T11:20:00Z",
    slotStart: "2026-08-07T08:30:00Z",
    slotEnd: "2026-08-07T09:00:00Z",
    patientSnapshot: {
      full_name: "Hoàng Văn Thái",
      phone_number: "0971 223 344",
      gender: "MALE",
      age: 42,
    },
  },
  {
    id: "app-rec-002",
    appointmentCode: "APT-PENDING-002",
    patientId: "pat-202",
    doctorId: "doc-01",
    doctorName: "BS. CKI Trần Văn Nam",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-01",
    specialtyName: "Khoa Tim Mạch",
    room: "Phòng 302 - Tầng 3",
    scheduleId: "sch-102",
    status: "PENDING_RECEPTIONIST_APPROVAL",
    bookingReason: "Thỉnh thoảng có cơn hồi hộp, nhịp tim nhanh 100 lần/phút lúc nghỉ ngơi.",
    patientNotes: "Có tiền sử cao huyết áp gia đình.",
    receptionistNotes: null,
    cancellationReason: null,
    expiresAt: "2026-08-06T15:00:00Z",
    confirmedAt: null,
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-05T12:00:00Z",
    updatedAt: "2026-08-05T12:00:00Z",
    slotStart: "2026-08-07T10:00:00Z",
    slotEnd: "2026-08-07T10:30:00Z",
    patientSnapshot: {
      full_name: "Vũ Thị Mai",
      phone_number: "0915 889 900",
      gender: "FEMALE",
      age: 51,
    },
  },
  {
    id: "app-rec-003",
    appointmentCode: "APT-PENDING-003",
    patientId: "pat-203",
    doctorId: "doc-03",
    doctorName: "BS. CKII Lê Thị Hương",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-03",
    specialtyName: "Khoa Nhi",
    room: "Phòng 108 - Tầng 1",
    scheduleId: "sch-103",
    status: "PENDING_RECEPTIONIST_APPROVAL",
    bookingReason: "Khám cho con trai 4 tuổi, sốt nhẹ 38 độ C kèm ho hắng hắt hơi 2 ngày.",
    patientNotes: "Cháu chưa uống kháng sinh, chỉ dùng hạ sốt Paracetamol.",
    receptionistNotes: null,
    cancellationReason: null,
    expiresAt: "2026-08-06T16:30:00Z",
    confirmedAt: null,
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-05T13:00:00Z",
    updatedAt: "2026-08-05T13:00:00Z",
    slotStart: "2026-08-07T14:00:00Z",
    slotEnd: "2026-08-07T14:30:00Z",
    patientSnapshot: {
      full_name: "Lê Hoàng Phúc (Mẹ: Nguyễn Thúy Hằng)",
      phone_number: "0934 556 677",
      gender: "MALE",
      age: 4,
      patientSubject: "RELATIVE",
      relationship: "Con trai",
    },
  },
];

export const MOCK_RECEPTION_HANDOVERS: Array<Record<string, unknown>> = [
  {
    id: "handover-001",
    reason: "Cần lễ tân hỗ trợ chọn bác sĩ chuyên khoa Thần kinh",
    summary: "Bệnh nhân báo đau đầu từng cơn bên phải kèm buồn nôn. AI nhận thấy độ tin cậy đề xuất chuyên khoa không đủ 80% nên chuyển điều phối viên.",
    createdAt: "2026-08-05T11:45:00Z",
    patientName: "Đặng Tiến Dũng",
    patientPhone: "0966 112 445",
  },
  {
    id: "handover-002",
    reason: "Yêu cầu đổi khung giờ đặc biệt ngoài giờ hành chính",
    summary: "Bệnh nhân bận công tác chỉ đi khám được sau 17h30 hoặc sáng Thứ 7. Lễ tân cần hỗ trợ liên hệ mở slot xếp lịch.",
    createdAt: "2026-08-05T12:30:00Z",
    patientName: "Đỗ Phương Thảo",
    patientPhone: "0944 887 766",
  },
];

export const MOCK_PATIENT_BOOKINGS: Appointment[] = [
  {
    id: "app-patient-001",
    appointmentCode: "APT-2026-8891",
    patientId: "pat-101",
    doctorId: "doc-01",
    doctorName: "BS. CKI Trần Văn Nam",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-01",
    specialtyName: "Khoa Tim Mạch",
    room: "Phòng 302 - Tầng 3",
    scheduleId: "sch-001",
    status: "CONFIRMED",
    bookingReason: "Tức ngực trái nhẹ khi leo cầu thang, kèm hồi hộp kéo dài 2 ngày.",
    patientNotes: "Có mang theo kết quả khám tim cũ.",
    receptionistNotes: "Đã chốt lịch hẹn.",
    cancellationReason: null,
    expiresAt: null,
    confirmedAt: "2026-08-05T08:30:00Z",
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-04T14:20:00Z",
    updatedAt: "2026-08-05T08:30:00Z",
    slotStart: "2026-08-06T09:00:00Z",
    slotEnd: "2026-08-06T09:30:00Z",
    patientSnapshot: {
      full_name: "Nguyễn Văn An",
      phone_number: "0912 345 678",
      gender: "MALE",
    },
  },
  {
    id: "app-patient-002",
    appointmentCode: "APT-2026-8892",
    patientId: "pat-101",
    doctorId: "doc-02",
    doctorName: "TS.BS Nguyễn Thanh Tùng",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-02",
    specialtyName: "Khoa Tiêu Hóa",
    room: "Phòng 205 - Tầng 2",
    scheduleId: "sch-002",
    status: "PENDING_RECEPTIONIST_APPROVAL",
    bookingReason: "Đau rát vùng thượng vị 3 ngày nay, ợ chua nhiều.",
    patientNotes: "Mong muốn khám ca sáng.",
    receptionistNotes: null,
    cancellationReason: null,
    expiresAt: "2026-08-06T12:00:00Z",
    confirmedAt: null,
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-05T10:15:00Z",
    updatedAt: "2026-08-05T10:15:00Z",
    slotStart: "2026-08-07T10:30:00Z",
    slotEnd: "2026-08-07T11:00:00Z",
    patientSnapshot: {
      full_name: "Nguyễn Văn An",
      phone_number: "0912 345 678",
      gender: "MALE",
    },
  },
  {
    id: "app-patient-003",
    appointmentCode: "APT-2026-8893",
    patientId: "pat-101",
    doctorId: "doc-03",
    doctorName: "BS. CKII Lê Thị Hương",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-03",
    specialtyName: "Khoa Nhi",
    room: "Phòng 108 - Tầng 1",
    scheduleId: "sch-003",
    status: "PENDING_PATIENT_CONFIRMATION",
    bookingReason: "Khám cho con trai 4 tuổi, sốt nhẹ 38 độ C.",
    patientNotes: "Cần chọn lịch thay thế từ lễ tân.",
    receptionistNotes: "Lễ tân đã chuyển lịch sang ca chiều.",
    cancellationReason: null,
    expiresAt: "2026-08-06T18:00:00Z",
    confirmedAt: null,
    cancelledAt: null,
    completedAt: null,
    createdAt: "2026-08-05T11:00:00Z",
    updatedAt: "2026-08-05T11:00:00Z",
    slotStart: "2026-08-07T14:00:00Z",
    slotEnd: "2026-08-07T14:30:00Z",
    patientSnapshot: {
      full_name: "Nguyễn Văn An (Khám cho con)",
      phone_number: "0912 345 678",
      gender: "MALE",
    },
  },
  {
    id: "app-patient-004",
    appointmentCode: "APT-2026-8890",
    patientId: "pat-101",
    doctorId: "doc-04",
    doctorName: "BS. CKI Đỗ Thu Trang",
    facilityId: "fac-01",
    facilityName: "Bệnh viện Đa khoa Trung tâm",
    facilityAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    specialtyId: "spec-04",
    specialtyName: "Khoa Nội Tổng Quát",
    room: "Phòng 101 - Tầng 1",
    scheduleId: "sch-000",
    status: "COMPLETED",
    bookingReason: "Khám sức khỏe tổng quát định kỳ.",
    patientNotes: "Đã hoàn thành khám.",
    receptionistNotes: "Đã hoàn thành.",
    cancellationReason: null,
    expiresAt: null,
    confirmedAt: "2026-07-20T09:00:00Z",
    cancelledAt: null,
    completedAt: "2026-07-20T10:30:00Z",
    createdAt: "2026-07-19T14:00:00Z",
    updatedAt: "2026-07-20T10:30:00Z",
    slotStart: "2026-07-20T09:00:00Z",
    slotEnd: "2026-07-20T09:30:00Z",
    patientSnapshot: {
      full_name: "Nguyễn Văn An",
      phone_number: "0912 345 678",
      gender: "MALE",
    },
  },
];
